# cargo.toml
[package]
name = "server-grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld-server"
path = "src/server.rs"

[[bin]]
name = "helloworld-web-client"
path = "src/web-client.rs"

[dependencies]
tonic = "0.8"
tonic-web = "0.5"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
http = "0.2"
hyper = "0.14"
bytes = "1.4.0"

[build-dependencies]
tonic-build = "0.8"